@startuml Users - Code Components

<style>
.error {
    BackgroundColor pink
}
</style>

hide empty members

title Создание пользователя
start

:Открыть страницу "Пользователи и роли";
:Нажать на кнопку "Добавить пользователя";
:Открыть страницы "Создать пользователя";

repeat :Ввод данных формы
    :Нажатие на кнопку "Создать";
    :Валидация данных;

backward: Отобразить ошибки валидации; <<error>>
repeat while (есть ошибки?) is (да) not (нет)

:Создать пользователя;
:Переход на страницу списка пользователей;

stop

@enduml