@startuml Channels - Code Components

hide empty members

enum ChannelReportGrouping <<Тип группировки отчета>> {
    NONE
    ROLE
    CLIENTS
    PROJECT_TYPE
    TOOLS
}

class ChannelReportQueryData <<DTO с параметрами отчета>> {
    + ChannelReportGrouping $grouping
    + Collection<ChannelReportColumnData> $columns
    + Carbon $dateFrom
    + Carbon $dateTo
    + bool $showInactive
    + bool $includeVat
}

class ChannelReportData <<DTO отчета, возвращаемое в компонент>> {
    + Collection<ChannelReportGroupData> $groups
    + Collection<field, value> $summary
}

class ChannelReportGroupData <<DTO группы отчета>> {
    + string $groupLabel - поле, по которому группируются данные
    + Collection<field, value> $rows
    + Collection<field, value> $summary
}

class ChannelReportColumnData <<DTO столбца отчета>> {
    + string $field
    + string $label
    + int $order
}

class ChannelReportService <<Сервис с логикой отчета>> {
    + getReportData(ChannelReportQueryData $queryData): ChannelReportData
}

class ChannelReportColumn extends Livewire.Component {
    + render()
}

class ChannelReport <<Fullpage Компонент Livewire для страницы "Каналы">> extends Livewire.Component {
    + ChannelReportQueryData $queryData
    + ChannelReportData $reportData
    - ChannelReportService $reportService

    + boot(): void
    + mount(): void
    + render(): void
    + getReportData(): void
}
note as ChannelReportNote
    Рендер таблицы выполняется по следующему алгоритму:
    {{
        !include channel_report_table_render.wsd
    }}
    Предполагается, что при отсутствии группировки, то в reportData будет только одна группа без groupLabel
end note



ChannelReportNote -> ChannelReport

ChannelReport --> ChannelReportQueryData
ChannelReport --> ChannelReportService
ChannelReportQueryData --> ChannelReportGrouping
ChannelReportQueryData --> ChannelReportColumnData
ChannelReportService --> ChannelReportQueryData
ChannelReportService --> ChannelReportData
ChannelReportData --> ChannelReportGroupData


@enduml