<svg
    width="13"
    height="11"
    viewBox="0 0 13 11"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {{ $attributes }}
>
    <rect
        y="4.5"
        width="13"
        height="2"
        rx="1"
        fill="currentColor"
    />
    <rect
        width="13"
        height="2"
        rx="1"
        fill="currentColor"
    />
    <rect
        y="9"
        width="13"
        height="2"
        rx="1"
        fill="currentColor"
    />
</svg>
