version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: casini
    volumes:
      - ../:/var/www/html
    networks:
      - casini-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: nginx:1.23-alpine
    container_name: casini_webserver
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - casini-network

  db:
    image: mariadb:10
    container_name: casini_db
    environment:
      MYSQL_DATABASE: casini
      MYSQL_USER: casini
      MYSQL_PASSWORD: casini
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - casini_dbdata:/var/lib/mysql
    networks:
      - casini-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: casini_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_HOST_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - casini-network

  node:
    image: node:23-alpine
    container_name: casini_nodejs
    environment:
      NODE_ENV: development
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    command: sh ./docker/start-node.sh
    ports:
      - "5173:5173"
    networks:
      - casini-network
    depends_on:
      - app

networks:
  casini-network:
    driver: bridge

volumes:
  casini_dbdata: